/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BotomationStandaloneSetup extends BotomationStandaloneSetupGenerated {

	public static void doSetup() {
		new BotomationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
