/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBotomationScopeProvider extends DelegatingScopeProvider {
}
