/**
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.botomation.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.imta.botomation.botomation.Botomation;
import org.imta.botomation.botomation.BotomationPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Botomation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BotomationImpl extends MinimalEObjectImpl.Container implements Botomation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BotomationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BotomationPackage.Literals.BOTOMATION;
  }

} //BotomationImpl
