/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BotomationAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/imta/botomation/parser/antlr/internal/InternalBotomation.tokens");
	}
}
