/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.imta.botomation.parser.antlr.internal.InternalBotomationParser;
import org.imta.botomation.services.BotomationGrammarAccess;

public class BotomationParser extends AbstractAntlrParser {

	@Inject
	private BotomationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBotomationParser createParser(XtextTokenStream stream) {
		return new InternalBotomationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Botomation";
	}

	public BotomationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BotomationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
