/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BotomationUiModule extends AbstractBotomationUiModule {

	public BotomationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
