/**
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.botomation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.imta.botomation.botomation.BotomationFactory
 * @model kind="package"
 * @generated
 */
public interface BotomationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "botomation";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imta.org/botomation/Botomation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "botomation";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BotomationPackage eINSTANCE = org.imta.botomation.botomation.impl.BotomationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.imta.botomation.botomation.impl.BotomationImpl <em>Botomation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.imta.botomation.botomation.impl.BotomationImpl
   * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getBotomation()
   * @generated
   */
  int BOTOMATION = 0;

  /**
   * The number of structural features of the '<em>Botomation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTOMATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.imta.botomation.botomation.impl.BrowserImpl <em>Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.imta.botomation.botomation.impl.BrowserImpl
   * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getBrowser()
   * @generated
   */
  int BROWSER = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER__ACTIONS = BOTOMATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER__NAME = BOTOMATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_FEATURE_COUNT = BOTOMATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.imta.botomation.botomation.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.imta.botomation.botomation.impl.ActionImpl
   * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getAction()
   * @generated
   */
  int ACTION = 2;

  /**
   * The feature id for the '<em><b>Open URL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__OPEN_URL = 0;

  /**
   * The feature id for the '<em><b>Verify Page Contains</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__VERIFY_PAGE_CONTAINS = 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.imta.botomation.botomation.impl.VerifyPageContainsImpl <em>Verify Page Contains</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.imta.botomation.botomation.impl.VerifyPageContainsImpl
   * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getVerifyPageContains()
   * @generated
   */
  int VERIFY_PAGE_CONTAINS = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_PAGE_CONTAINS__TYPE = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_PAGE_CONTAINS__TARGET = 1;

  /**
   * The number of structural features of the '<em>Verify Page Contains</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_PAGE_CONTAINS_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.imta.botomation.botomation.Botomation <em>Botomation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Botomation</em>'.
   * @see org.imta.botomation.botomation.Botomation
   * @generated
   */
  EClass getBotomation();

  /**
   * Returns the meta object for class '{@link org.imta.botomation.botomation.Browser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser</em>'.
   * @see org.imta.botomation.botomation.Browser
   * @generated
   */
  EClass getBrowser();

  /**
   * Returns the meta object for the containment reference list '{@link org.imta.botomation.botomation.Browser#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.imta.botomation.botomation.Browser#getActions()
   * @see #getBrowser()
   * @generated
   */
  EReference getBrowser_Actions();

  /**
   * Returns the meta object for the attribute '{@link org.imta.botomation.botomation.Browser#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.imta.botomation.botomation.Browser#getName()
   * @see #getBrowser()
   * @generated
   */
  EAttribute getBrowser_Name();

  /**
   * Returns the meta object for class '{@link org.imta.botomation.botomation.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.imta.botomation.botomation.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.imta.botomation.botomation.Action#getOpenURL <em>Open URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Open URL</em>'.
   * @see org.imta.botomation.botomation.Action#getOpenURL()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_OpenURL();

  /**
   * Returns the meta object for the containment reference '{@link org.imta.botomation.botomation.Action#getVerifyPageContains <em>Verify Page Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Verify Page Contains</em>'.
   * @see org.imta.botomation.botomation.Action#getVerifyPageContains()
   * @see #getAction()
   * @generated
   */
  EReference getAction_VerifyPageContains();

  /**
   * Returns the meta object for class '{@link org.imta.botomation.botomation.VerifyPageContains <em>Verify Page Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify Page Contains</em>'.
   * @see org.imta.botomation.botomation.VerifyPageContains
   * @generated
   */
  EClass getVerifyPageContains();

  /**
   * Returns the meta object for the attribute '{@link org.imta.botomation.botomation.VerifyPageContains#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.imta.botomation.botomation.VerifyPageContains#getType()
   * @see #getVerifyPageContains()
   * @generated
   */
  EAttribute getVerifyPageContains_Type();

  /**
   * Returns the meta object for the attribute '{@link org.imta.botomation.botomation.VerifyPageContains#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.imta.botomation.botomation.VerifyPageContains#getTarget()
   * @see #getVerifyPageContains()
   * @generated
   */
  EAttribute getVerifyPageContains_Target();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BotomationFactory getBotomationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.imta.botomation.botomation.impl.BotomationImpl <em>Botomation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.imta.botomation.botomation.impl.BotomationImpl
     * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getBotomation()
     * @generated
     */
    EClass BOTOMATION = eINSTANCE.getBotomation();

    /**
     * The meta object literal for the '{@link org.imta.botomation.botomation.impl.BrowserImpl <em>Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.imta.botomation.botomation.impl.BrowserImpl
     * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getBrowser()
     * @generated
     */
    EClass BROWSER = eINSTANCE.getBrowser();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BROWSER__ACTIONS = eINSTANCE.getBrowser_Actions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROWSER__NAME = eINSTANCE.getBrowser_Name();

    /**
     * The meta object literal for the '{@link org.imta.botomation.botomation.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.imta.botomation.botomation.impl.ActionImpl
     * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Open URL</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__OPEN_URL = eINSTANCE.getAction_OpenURL();

    /**
     * The meta object literal for the '<em><b>Verify Page Contains</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__VERIFY_PAGE_CONTAINS = eINSTANCE.getAction_VerifyPageContains();

    /**
     * The meta object literal for the '{@link org.imta.botomation.botomation.impl.VerifyPageContainsImpl <em>Verify Page Contains</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.imta.botomation.botomation.impl.VerifyPageContainsImpl
     * @see org.imta.botomation.botomation.impl.BotomationPackageImpl#getVerifyPageContains()
     * @generated
     */
    EClass VERIFY_PAGE_CONTAINS = eINSTANCE.getVerifyPageContains();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY_PAGE_CONTAINS__TYPE = eINSTANCE.getVerifyPageContains_Type();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY_PAGE_CONTAINS__TARGET = eINSTANCE.getVerifyPageContains_Target();

  }

} //BotomationPackage
