/**
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.botomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Botomation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.imta.botomation.botomation.BotomationPackage#getBotomation()
 * @model
 * @generated
 */
public interface Botomation extends EObject
{
} // Botomation
