/**
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.botomation;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.imta.botomation.botomation.BotomationPackage
 * @generated
 */
public interface BotomationFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BotomationFactory eINSTANCE = org.imta.botomation.botomation.impl.BotomationFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Botomation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Botomation</em>'.
   * @generated
   */
  Botomation createBotomation();

  /**
   * Returns a new object of class '<em>Browser</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Browser</em>'.
   * @generated
   */
  Browser createBrowser();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Verify Page Contains</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Verify Page Contains</em>'.
   * @generated
   */
  VerifyPageContains createVerifyPageContains();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BotomationPackage getBotomationPackage();

} //BotomationFactory
