/**
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.botomation;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Browser</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.imta.botomation.botomation.Browser#getActions <em>Actions</em>}</li>
 *   <li>{@link org.imta.botomation.botomation.Browser#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.imta.botomation.botomation.BotomationPackage#getBrowser()
 * @model
 * @generated
 */
public interface Browser extends Botomation
{
  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.imta.botomation.botomation.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.imta.botomation.botomation.BotomationPackage#getBrowser_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.imta.botomation.botomation.BotomationPackage#getBrowser_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.imta.botomation.botomation.Browser#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Browser
