/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.imta.botomation.ui.internal.BotomationActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BotomationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BotomationActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BotomationActivator activator = BotomationActivator.getInstance();
		return activator != null ? activator.getInjector(BotomationActivator.ORG_IMTA_BOTOMATION_BOTOMATION) : null;
	}

}
