/*
 * generated by Xtext 2.32.0
 */
package org.imta.botomation.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.imta.botomation.ui.internal.BotomationActivator;

public class BotomationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BotomationActivator.getInstance().getInjector("org.imta.botomation.Botomation");
	}

}
